import type { SectionType } from "@prisma/client";

type TemplateRegistryEntry = {
  key: string;
  name: string;
  description: string;
  mood: string;
  // "free" templates are available on every plan. "premium" ones require
  // Together, Forever, or an admin account — enforced server-side in
  // updateTemplateThemeAction, never only in the UI.
  // The original five stay free so no existing site can lose its design.
  tier: "free" | "premium";
  previewGradient: string;
  heroVariant: "classic" | "split" | "cinematic" | "editorial" | "celebration" | "destination";
  cardVariant: "glass" | "soft" | "outline" | "shadow";
  navigationVariant: "pill" | "underline" | "ghost";
  themeDefaults: {
    paletteKey: string;
    headingFontKey: string;
    bodyFontKey: string;
    primaryColor: string;
    accentColor: string;
    backgroundColor: string;
    surfaceColor: string;
    textColor: string;
    mutedColor: string;
    borderRadius: string;
    buttonVariant: string;
    shadowStyle: string;
  };
  supportedSections: SectionType[];
};

export const templateRegistry: TemplateRegistryEntry[] = [
  {
    key: "classic-elegant",
    tier: "free",
    name: "Classic Elegant",
    description: "A luminous editorial layout with refined serif typography and warm ivory surfaces.",
    mood: "Timeless luxury",
    previewGradient: "linear-gradient(135deg, #fffaf5 0%, #f1e7dc 45%, #d8b98c 100%)",
    heroVariant: "classic",
    cardVariant: "glass",
    navigationVariant: "pill",
    themeDefaults: {
      paletteKey: "champagne",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#6e4f35",
      accentColor: "#b88c4a",
      backgroundColor: "#fdf8f3",
      surfaceColor: "#fffaf6",
      textColor: "#2b1a18",
      mutedColor: "#8b6f68",
      borderRadius: "2rem",
      buttonVariant: "solid",
      shadowStyle: "glow",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "floral-romantic",
    tier: "free",
    name: "Floral Romantic",
    description: "Soft petals, layered blush gradients, and a dreamy tone built for emotionally rich storytelling.",
    mood: "Garden romance",
    previewGradient: "linear-gradient(135deg, #fff8fb 0%, #f9dce5 40%, #f0b3c6 100%)",
    heroVariant: "editorial",
    cardVariant: "soft",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "petal",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#7e4b58",
      accentColor: "#d98aa2",
      backgroundColor: "#fff7fa",
      surfaceColor: "#fff9fc",
      textColor: "#3d2730",
      mutedColor: "#88656f",
      borderRadius: "2.2rem",
      buttonVariant: "soft",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "minimal-luxury",
    tier: "free",
    name: "Minimal Luxury",
    description: "A crisp, restrained system with generous whitespace, elegant contrast, and premium restraint.",
    mood: "Modern luxury",
    previewGradient: "linear-gradient(135deg, #ffffff 0%, #f1f0ed 50%, #c8c0b4 100%)",
    heroVariant: "split",
    cardVariant: "outline",
    navigationVariant: "ghost",
    themeDefaults: {
      paletteKey: "stone",
      headingFontKey: "luxe",
      bodyFontKey: "body",
      primaryColor: "#2f2b28",
      accentColor: "#9f8360",
      backgroundColor: "#fcfbf8",
      surfaceColor: "#ffffff",
      textColor: "#1f1a17",
      mutedColor: "#6e6862",
      borderRadius: "1.5rem",
      buttonVariant: "outline",
      shadowStyle: "none",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "cinematic-modern",
    tier: "free",
    name: "Cinematic Modern",
    description: "Darker, moodier layers designed for video-led storytelling and dramatic event presentation.",
    mood: "Cinematic celebration",
    previewGradient: "linear-gradient(135deg, #1f1c2c 0%, #3a2f4f 45%, #7f5f89 100%)",
    heroVariant: "cinematic",
    cardVariant: "glass",
    navigationVariant: "pill",
    themeDefaults: {
      paletteKey: "midnight",
      headingFontKey: "luxe",
      bodyFontKey: "body",
      primaryColor: "#f2d4ab",
      accentColor: "#c79559",
      backgroundColor: "#140f18",
      surfaceColor: "#201625",
      textColor: "#f9f3ec",
      mutedColor: "#cdbdb5",
      borderRadius: "1.75rem",
      buttonVariant: "solid",
      shadowStyle: "glow",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "traditional-celebration",
    tier: "free",
    name: "Traditional Celebration",
    description: "A vibrant cultural template that balances ceremony richness with practical event guidance.",
    mood: "Festive heritage",
    previewGradient: "linear-gradient(135deg, #fff6ec 0%, #f4d8b2 45%, #c45d24 100%)",
    heroVariant: "celebration",
    cardVariant: "shadow",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "saffron",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#8b3a10",
      accentColor: "#cf7a24",
      backgroundColor: "#fff7ef",
      surfaceColor: "#fffdf8",
      textColor: "#341b14",
      mutedColor: "#7d5b4d",
      borderRadius: "1.9rem",
      buttonVariant: "solid",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "temple-gold",
    tier: "premium",
    name: "Temple Gopuram",
    description: "Carved gopuram towers, a hanging mango-leaf toran and peacocks in terracotta, temple teal and gold \u2014 the full traditional South Indian invitation.",
    mood: "South Indian temple",
    previewGradient: "linear-gradient(135deg, #fdf6ec 0%, #e8b98a 40%, #2f6f6b 100%)",
    heroVariant: "celebration",
    cardVariant: "shadow",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "gopuram",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#b4552e",
      accentColor: "#2f6f6b",
      backgroundColor: "#fdf6ec",
      surfaceColor: "#fffdf8",
      textColor: "#33211a",
      mutedColor: "#7d6152",
      borderRadius: "1.75rem",
      buttonVariant: "solid",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "marigold-festive",
    tier: "premium",
    name: "Haveli Marigold",
    description: "Cusped palace arches, pierced jaali, hanging jhoomar lamps and ceremonial elephants in deep rose and gold \u2014 a North Indian shaadi with the volume up.",
    mood: "North Indian palace",
    previewGradient: "linear-gradient(135deg, #fdf5ec 0%, #e7bb62 38%, #a3234e 100%)",
    heroVariant: "celebration",
    cardVariant: "soft",
    navigationVariant: "pill",
    themeDefaults: {
      paletteKey: "haveli",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#a3234e",
      accentColor: "#c99029",
      backgroundColor: "#fdf5ec",
      surfaceColor: "#fffdf8",
      textColor: "#2e1420",
      mutedColor: "#7f5866",
      borderRadius: "2.1rem",
      buttonVariant: "solid",
      shadowStyle: "glow",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "emerald-pearl",
    tier: "premium",
    name: "Emerald & Pearl",
    description: "Emerald, pearl and restrained geometry: an unfigured palette suited to Nikah and Walima celebrations.",
    mood: "Islamic elegance",
    previewGradient: "linear-gradient(135deg, #f6fbf8 0%, #cfe6d8 45%, #0f5c46 100%)",
    heroVariant: "editorial",
    cardVariant: "glass",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "emerald",
      headingFontKey: "luxe",
      bodyFontKey: "body",
      primaryColor: "#0f5c46",
      accentColor: "#b99a5b",
      backgroundColor: "#f8fbf9",
      surfaceColor: "#ffffff",
      textColor: "#12241d",
      mutedColor: "#5f7a70",
      borderRadius: "1.5rem",
      buttonVariant: "outline",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "chapel-ivory",
    tier: "premium",
    name: "Chapel Ivory",
    description: "Ivory, dove grey and stained-glass blue with quiet symmetry, shaped around a church ceremony and reception.",
    mood: "Christian classic",
    previewGradient: "linear-gradient(135deg, #fcfcfa 0%, #e4e7ee 45%, #46618f 100%)",
    heroVariant: "classic",
    cardVariant: "outline",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "chapel",
      headingFontKey: "luxe",
      bodyFontKey: "body",
      primaryColor: "#3d5680",
      accentColor: "#8f9bb3",
      backgroundColor: "#fcfcfb",
      surfaceColor: "#ffffff",
      textColor: "#1e2430",
      mutedColor: "#6b7280",
      borderRadius: "1.25rem",
      buttonVariant: "outline",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "crimson-gold",
    tier: "premium",
    name: "Crimson & Gold",
    description: "Lacquer crimson and leaf gold with generous negative space, made for tea ceremonies and banquet evenings.",
    mood: "Chinese double happiness",
    previewGradient: "linear-gradient(135deg, #fff7f4 0%, #f0c9a0 40%, #b3121e 100%)",
    heroVariant: "cinematic",
    cardVariant: "shadow",
    navigationVariant: "pill",
    themeDefaults: {
      paletteKey: "crimson",
      headingFontKey: "sc",
      bodyFontKey: "body",
      primaryColor: "#b3121e",
      accentColor: "#c9a227",
      backgroundColor: "#fffaf7",
      surfaceColor: "#fffdfb",
      textColor: "#2a1010",
      mutedColor: "#7d5350",
      borderRadius: "1.6rem",
      buttonVariant: "solid",
      shadowStyle: "glow",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "desert-neutral",
    tier: "premium",
    name: "Desert Neutral",
    description: "Sand, oud brown and muted brass: an understated palette for Khaleeji and wider Arabic celebrations.",
    mood: "Arabic understatement",
    previewGradient: "linear-gradient(135deg, #fdfaf5 0%, #e6d7c1 45%, #6f5137 100%)",
    heroVariant: "editorial",
    cardVariant: "glass",
    navigationVariant: "ghost",
    themeDefaults: {
      paletteKey: "oud",
      headingFontKey: "arabic",
      bodyFontKey: "body",
      primaryColor: "#6f5137",
      accentColor: "#a98756",
      backgroundColor: "#fdfbf7",
      surfaceColor: "#fffefb",
      textColor: "#241a12",
      mutedColor: "#7a6a58",
      borderRadius: "1.4rem",
      buttonVariant: "outline",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "kolam-blush",
    tier: "premium",
    name: "Kolam Blush",
    description: "Warm greige, rose and sage with a drawn kolam and a botanical monogram \u2014 Tamil invitation typography, in a soft editorial register.",
    mood: "Tamil invitation",
    previewGradient: "linear-gradient(135deg, #f6f1ec 0%, #e3d7cd 45%, #c2687f 100%)",
    heroVariant: "editorial",
    cardVariant: "soft",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "blush-kolam",
      // Tamil face, so a couple can set their names in Tamil script and have
      // them render. Every other template is Latin-only by default.
      headingFontKey: "tamil",
      bodyFontKey: "body",
      primaryColor: "#c2687f",
      accentColor: "#93ab8a",
      backgroundColor: "#f6f1ec",
      surfaceColor: "#fdfaf7",
      textColor: "#3a2b28",
      mutedColor: "#8a7770",
      borderRadius: "1.8rem",
      buttonVariant: "solid",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "shoreline-blue",
    tier: "premium",
    name: "Shoreline Blue",
    description: "Aegean blue against whitewash, for a coastal wedding where the view does the talking. Photo-led, with no ornament to compete with it.",
    mood: "Mediterranean coast",
    previewGradient: "linear-gradient(135deg, #f7fbfd 0%, #bcd8e6 42%, #1d5d86 100%)",
    heroVariant: "destination",
    cardVariant: "glass",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "aegean",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#1d5d86",
      accentColor: "#3f93b8",
      backgroundColor: "#f8fbfd",
      surfaceColor: "#ffffff",
      textColor: "#12242e",
      mutedColor: "#5c7684",
      borderRadius: "1.4rem",
      buttonVariant: "solid",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "olive-grove",
    tier: "premium",
    name: "Olive Grove",
    description: "Sun-warmed stone, olive and wheat for a villa or vineyard wedding in the hills.",
    mood: "Tuscan countryside",
    previewGradient: "linear-gradient(135deg, #fdfaf2 0%, #ddd0ac 44%, #6d7546 100%)",
    heroVariant: "destination",
    cardVariant: "soft",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "olive",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#6d7546",
      accentColor: "#b08d46",
      backgroundColor: "#fdfaf3",
      surfaceColor: "#fffefa",
      textColor: "#2c2a1d",
      mutedColor: "#77725c",
      borderRadius: "1.6rem",
      buttonVariant: "solid",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "palm-and-teak",
    tier: "premium",
    name: "Palm & Teak",
    description: "Teak, deep palm and sunset amber for a tropical wedding in Bali, Kerala or Thailand.",
    mood: "Tropical evening",
    previewGradient: "linear-gradient(135deg, #fdf7f1 0%, #e0b384 42%, #2f4a3c 100%)",
    heroVariant: "destination",
    cardVariant: "shadow",
    navigationVariant: "pill",
    themeDefaults: {
      paletteKey: "palm",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#2f4a3c",
      accentColor: "#c98a4b",
      backgroundColor: "#fdf8f2",
      surfaceColor: "#fffdf9",
      textColor: "#20211c",
      mutedColor: "#6f7168",
      borderRadius: "1.7rem",
      buttonVariant: "solid",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "atoll-white",
    tier: "premium",
    name: "Atoll White",
    description: "Lagoon aqua and bleached sand for an overwater or beach ceremony, kept pale so the water stays the brightest thing on the page.",
    mood: "Island lagoon",
    previewGradient: "linear-gradient(135deg, #fbfdfd 0%, #cfe8e6 44%, #4d9c96 100%)",
    heroVariant: "destination",
    cardVariant: "glass",
    navigationVariant: "ghost",
    themeDefaults: {
      paletteKey: "atoll",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#3d857f",
      accentColor: "#8cc2bc",
      backgroundColor: "#fafdfd",
      surfaceColor: "#ffffff",
      textColor: "#1b2b2a",
      mutedColor: "#5f7d7a",
      borderRadius: "1.3rem",
      buttonVariant: "solid",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
];

// Premium templates require a paid plan. Unknown keys are treated as premium
// (fail-closed) so a typo can never silently hand out a paid design.
export function isPremiumTemplate(templateKey: string): boolean {
  const template = templateRegistry.find((entry) => entry.key === templateKey);
  return template ? template.tier === "premium" : true;
}

export function findTemplateByKey(templateKey: string) {
  return (
    templateRegistry.find((template) => template.key === templateKey) ?? templateRegistry[0]
  );
}
