import type { SectionType } from "@prisma/client";

type TemplateRegistryEntry = {
  key: string;
  name: string;
  description: string;
  mood: string;
  // "free" templates are available on every plan. "premium" ones require
  // Together, Forever, or an admin account — enforced server-side in
  // updateTemplateThemeAction, never only in the UI.
  // The original five stay free so no existing site can lose its design.
  tier: "free" | "premium";
  previewGradient: string;
  heroVariant: "classic" | "split" | "cinematic" | "editorial" | "celebration";
  cardVariant: "glass" | "soft" | "outline" | "shadow";
  navigationVariant: "pill" | "underline" | "ghost";
  themeDefaults: {
    paletteKey: string;
    headingFontKey: string;
    bodyFontKey: string;
    primaryColor: string;
    accentColor: string;
    backgroundColor: string;
    surfaceColor: string;
    textColor: string;
    mutedColor: string;
    borderRadius: string;
    buttonVariant: string;
    shadowStyle: string;
  };
  supportedSections: SectionType[];
};

export const templateRegistry: TemplateRegistryEntry[] = [
  {
    key: "classic-elegant",
    tier: "free",
    name: "Classic Elegant",
    description: "A luminous editorial layout with refined serif typography and warm ivory surfaces.",
    mood: "Timeless luxury",
    previewGradient: "linear-gradient(135deg, #fffaf5 0%, #f1e7dc 45%, #d8b98c 100%)",
    heroVariant: "classic",
    cardVariant: "glass",
    navigationVariant: "pill",
    themeDefaults: {
      paletteKey: "champagne",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#6e4f35",
      accentColor: "#b88c4a",
      backgroundColor: "#fdf8f3",
      surfaceColor: "#fffaf6",
      textColor: "#2b1a18",
      mutedColor: "#8b6f68",
      borderRadius: "2rem",
      buttonVariant: "solid",
      shadowStyle: "glow",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "floral-romantic",
    tier: "free",
    name: "Floral Romantic",
    description: "Soft petals, layered blush gradients, and a dreamy tone built for emotionally rich storytelling.",
    mood: "Garden romance",
    previewGradient: "linear-gradient(135deg, #fff8fb 0%, #f9dce5 40%, #f0b3c6 100%)",
    heroVariant: "editorial",
    cardVariant: "soft",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "petal",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#7e4b58",
      accentColor: "#d98aa2",
      backgroundColor: "#fff7fa",
      surfaceColor: "#fff9fc",
      textColor: "#3d2730",
      mutedColor: "#88656f",
      borderRadius: "2.2rem",
      buttonVariant: "soft",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "minimal-luxury",
    tier: "free",
    name: "Minimal Luxury",
    description: "A crisp, restrained system with generous whitespace, elegant contrast, and premium restraint.",
    mood: "Modern luxury",
    previewGradient: "linear-gradient(135deg, #ffffff 0%, #f1f0ed 50%, #c8c0b4 100%)",
    heroVariant: "split",
    cardVariant: "outline",
    navigationVariant: "ghost",
    themeDefaults: {
      paletteKey: "stone",
      headingFontKey: "luxe",
      bodyFontKey: "body",
      primaryColor: "#2f2b28",
      accentColor: "#9f8360",
      backgroundColor: "#fcfbf8",
      surfaceColor: "#ffffff",
      textColor: "#1f1a17",
      mutedColor: "#6e6862",
      borderRadius: "1.5rem",
      buttonVariant: "outline",
      shadowStyle: "none",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "cinematic-modern",
    tier: "free",
    name: "Cinematic Modern",
    description: "Darker, moodier layers designed for video-led storytelling and dramatic event presentation.",
    mood: "Cinematic celebration",
    previewGradient: "linear-gradient(135deg, #1f1c2c 0%, #3a2f4f 45%, #7f5f89 100%)",
    heroVariant: "cinematic",
    cardVariant: "glass",
    navigationVariant: "pill",
    themeDefaults: {
      paletteKey: "midnight",
      headingFontKey: "luxe",
      bodyFontKey: "body",
      primaryColor: "#f2d4ab",
      accentColor: "#c79559",
      backgroundColor: "#140f18",
      surfaceColor: "#201625",
      textColor: "#f9f3ec",
      mutedColor: "#cdbdb5",
      borderRadius: "1.75rem",
      buttonVariant: "solid",
      shadowStyle: "glow",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "traditional-celebration",
    tier: "free",
    name: "Traditional Celebration",
    description: "A vibrant cultural template that balances ceremony richness with practical event guidance.",
    mood: "Festive heritage",
    previewGradient: "linear-gradient(135deg, #fff6ec 0%, #f4d8b2 45%, #c45d24 100%)",
    heroVariant: "celebration",
    cardVariant: "shadow",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "saffron",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#8b3a10",
      accentColor: "#cf7a24",
      backgroundColor: "#fff7ef",
      surfaceColor: "#fffdf8",
      textColor: "#341b14",
      mutedColor: "#7d5b4d",
      borderRadius: "1.9rem",
      buttonVariant: "solid",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "temple-gold",
    tier: "premium",
    name: "Temple Gold",
    description: "Deep kumkum red and temple gold with carved-stone warmth, built for multi-day South Indian celebrations.",
    mood: "South Indian heritage",
    previewGradient: "linear-gradient(135deg, #fff8ee 0%, #f0d9a8 45%, #8c1f1f 100%)",
    heroVariant: "celebration",
    cardVariant: "shadow",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "kumkum",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#8c1f1f",
      accentColor: "#c9962f",
      backgroundColor: "#fff8f0",
      surfaceColor: "#fffdf7",
      textColor: "#2e1410",
      mutedColor: "#7c554a",
      borderRadius: "1.75rem",
      buttonVariant: "solid",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "marigold-festive",
    tier: "premium",
    name: "Marigold Festive",
    description: "Marigold orange against rose pink and mehendi green, tuned for the colour and noise of a North Indian shaadi.",
    mood: "North Indian celebration",
    previewGradient: "linear-gradient(135deg, #fff6e8 0%, #f7c65f 40%, #d64a6a 100%)",
    heroVariant: "celebration",
    cardVariant: "soft",
    navigationVariant: "pill",
    themeDefaults: {
      paletteKey: "marigold",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#c2385c",
      accentColor: "#e8a020",
      backgroundColor: "#fff8f2",
      surfaceColor: "#fffcf6",
      textColor: "#33161f",
      mutedColor: "#8a5f6a",
      borderRadius: "2.1rem",
      buttonVariant: "solid",
      shadowStyle: "glow",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "emerald-pearl",
    tier: "premium",
    name: "Emerald & Pearl",
    description: "Emerald, pearl and restrained geometry — an unfigured palette suited to Nikah and Walima celebrations.",
    mood: "Islamic elegance",
    previewGradient: "linear-gradient(135deg, #f6fbf8 0%, #cfe6d8 45%, #0f5c46 100%)",
    heroVariant: "editorial",
    cardVariant: "glass",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "emerald",
      headingFontKey: "luxe",
      bodyFontKey: "body",
      primaryColor: "#0f5c46",
      accentColor: "#b99a5b",
      backgroundColor: "#f8fbf9",
      surfaceColor: "#ffffff",
      textColor: "#12241d",
      mutedColor: "#5f7a70",
      borderRadius: "1.5rem",
      buttonVariant: "outline",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "chapel-ivory",
    tier: "premium",
    name: "Chapel Ivory",
    description: "Ivory, dove grey and stained-glass blue with quiet symmetry, shaped around a church ceremony and reception.",
    mood: "Christian classic",
    previewGradient: "linear-gradient(135deg, #fcfcfa 0%, #e4e7ee 45%, #46618f 100%)",
    heroVariant: "classic",
    cardVariant: "outline",
    navigationVariant: "underline",
    themeDefaults: {
      paletteKey: "chapel",
      headingFontKey: "luxe",
      bodyFontKey: "body",
      primaryColor: "#3d5680",
      accentColor: "#8f9bb3",
      backgroundColor: "#fcfcfb",
      surfaceColor: "#ffffff",
      textColor: "#1e2430",
      mutedColor: "#6b7280",
      borderRadius: "1.25rem",
      buttonVariant: "outline",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "crimson-gold",
    tier: "premium",
    name: "Crimson & Gold",
    description: "Lacquer crimson and leaf gold with generous negative space, made for tea ceremonies and banquet evenings.",
    mood: "Chinese double happiness",
    previewGradient: "linear-gradient(135deg, #fff7f4 0%, #f0c9a0 40%, #b3121e 100%)",
    heroVariant: "cinematic",
    cardVariant: "shadow",
    navigationVariant: "pill",
    themeDefaults: {
      paletteKey: "crimson",
      headingFontKey: "display",
      bodyFontKey: "body",
      primaryColor: "#b3121e",
      accentColor: "#c9a227",
      backgroundColor: "#fffaf7",
      surfaceColor: "#fffdfb",
      textColor: "#2a1010",
      mutedColor: "#7d5350",
      borderRadius: "1.6rem",
      buttonVariant: "solid",
      shadowStyle: "glow",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
  {
    key: "desert-neutral",
    tier: "premium",
    name: "Desert Neutral",
    description: "Sand, oud brown and muted brass — an understated palette for Khaleeji and wider Arabic celebrations.",
    mood: "Arabic understatement",
    previewGradient: "linear-gradient(135deg, #fdfaf5 0%, #e6d7c1 45%, #6f5137 100%)",
    heroVariant: "editorial",
    cardVariant: "glass",
    navigationVariant: "ghost",
    themeDefaults: {
      paletteKey: "oud",
      headingFontKey: "luxe",
      bodyFontKey: "body",
      primaryColor: "#6f5137",
      accentColor: "#a98756",
      backgroundColor: "#fdfbf7",
      surfaceColor: "#fffefb",
      textColor: "#241a12",
      mutedColor: "#7a6a58",
      borderRadius: "1.4rem",
      buttonVariant: "outline",
      shadowStyle: "card",
    },
    supportedSections: [
      "HERO",
      "STORY",
      "EVENTS",
      "SCHEDULE",
      "TIDBITS",
      "DRESS_CODE",
      "EXPERIENCE",
      "GALLERY",
      "VIDEOS",
      "REGISTRY",
      "RSVP",
      "MEMORIES",
      "MESSAGES",
    ],
  },
];

// Premium templates require a paid plan. Unknown keys are treated as premium
// (fail-closed) so a typo can never silently hand out a paid design.
export function isPremiumTemplate(templateKey: string): boolean {
  const template = templateRegistry.find((entry) => entry.key === templateKey);
  return template ? template.tier === "premium" : true;
}

export function findTemplateByKey(templateKey: string) {
  return (
    templateRegistry.find((template) => template.key === templateKey) ?? templateRegistry[0]
  );
}
